# Generated by Django 5.1.6 on 2025-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_groupchat_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
