# Generated by Django 5.1.6 on 2025-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
